name: 'AWS ECR tag'
description: 'Tag remote ecr imag'
inputs:
  access_key_id:
    description: 'AWS access key id'
    required: true
    default: ''
  secret_access_key:
    description: 'AWS access key secret'
    required: true
    default: ''
  region:
    description: 'AWS region'
    required: true
    default: 'us-east-1'
  ecr_repository:
    description: 'ECR repository name'
    required: true
    default: 'latest'
  ecr_tag:
    description: 'ECR existing tag to use as source'
    required: true
    default: 'latest'
  tag:
    description: 'New tag to add to ECR image'
    required: true
    default: 'latest'
outputs:
  digest:
    description: 'Digest of tagged ECR image'
runs:
  using: 'node12'
  main: 'index.js'